services:
  - type: web
    name: wellnest-backend
    env: node
    buildCommand: |
      npm install
      mkdir -p /opt/render/.cache/puppeteer
      npx puppeteer browsers install chrome --path /opt/render/.cache/puppeteer
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /opt/render/.cache/puppeteer/chrome/linux-141.0.7390.122/chrome-linux64/chrome
