services:
  - type: web
    name: wellnest-backend
    env: node
    buildCommand: npm install --production=false && npx puppeteer browsers install chrome
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /opt/render/.cache/puppeteer/chrome/linux-141.0.7390.122/chrome-linux64/chrome
